namespace: kuadrant-system

catalogSource:
  sourceType: grpc
  displayName: "RHCL Operators"
  publisher: grpc
  pollInterval: 45m

subscription:
  channel: stable
  installPlanApproval: Automatic
  name: rhcl-operator
  startingCSV: rhcl-operator.v1.0.0
  source: redhat-operators
  sourceNamespace: openshift-marketplace