kind: Secret
apiVersion: v1
metadata:
  name: members-db
stringData:
  POSTGRESQL_DATABASE: sampledb
  POSTGRESQL_PASSWORD:
  POSTGRESQL_USER:
  DB_CONNECTION: 'jdbc:postgresql://{{ include "membersdb-helm.fullname" . }}:5432/sampledb'
type: Opaque