apiVersion: v1
kind: Secret
metadata:
  name: members-db
stringData:
  POSTGRESQL_DATABASE: sampledb
  POSTGRESQL_PASSWORD: {{ db_user }}
  POSTGRESQL_USER: {{ db_password }}
  DB_CONNECTION: 'jdbc:postgresql://{{ include "membersdb-helm.fullname" . }}:5432/sampledb'
type: Opaque